weights: best.pt
cfg: models/SRyolo_MF.yaml
super: true
data: data/SRvedai.yaml
hyp: data/hyp.scratch.yaml
epochs: 3000
ch_steam: 3
ch: 3
input_mode: RGB
batch_size: 4
train_img_size: 1024
test_img_size: 800
hr_input: true
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: 0,1
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 4
project: runs/train
entity: null
name: exp
exist_ok: false
quad: false
linear_lr: false
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
world_size: 1
global_rank: -1
img_size:
- 1024
- 800
save_dir: runs/train/exp3
total_batch_size: 4
